os: linux
dist: focal
group: edge
env:
  global:
    # FOO
    - secure: "BrT4kNop0hw9os7NBQiVj2ZlY2Q0MzZmYTUwNThjZWQ="
keys:
  - DEV_TEST
script:
  - echo $TEST
  - echo $TRAVIS_DEV_TEST
  - echo $TRAVIS_REPO_PRIVATE
